/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as OgRouteImport } from './routes/og'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthDashboardRouteRouteImport } from './routes/_auth/dashboard/route'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as BabyPublicIdRouteRouteImport } from './routes/baby/$publicId/route'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthDashboardSettingsRouteImport } from './routes/_auth/dashboard/settings'
import { Route as AuthDashboardAddRouteImport } from './routes/_auth/dashboard_.add'
import { Route as AuthDashboardAdminRouteImport } from './routes/_auth/dashboard_.admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCachePurgeRouteImport } from './routes/api/cache/purge'
import { Route as BabyPublicIdIndexRouteImport } from './routes/baby/$publicId/index'
import { Route as BabyPublicIdPhotoRouteImport } from './routes/baby/$publicId/photo'
import { Route as BabyPublicIdPostRouteImport } from './routes/baby/$publicId/post'
import { Route as BabyPublicIdSettingsRouteImport } from './routes/baby/$publicId/settings'
import { Route as BabyPublicIdShareRouteImport } from './routes/baby/$publicId/share'
import { Route as BabyManifest_idRouteImport } from './routes/baby/manifest/$_id'
import { Route as OgBabyPublicIdRouteImport } from './routes/og.baby.$publicId'
import { Route as BabyPublicIdUpdatesUpdateIdPhotoRouteImport } from './routes/baby/$publicId/updates.$updateId.photo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRouteRoute = AuthDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BabyPublicIdRouteRoute = BabyPublicIdRouteRouteImport.update({
  id: '/baby/$publicId',
  path: '/baby/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardSettingsRoute = AuthDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthDashboardAddRoute = AuthDashboardAddRouteImport.update({
  id: '/dashboard_/add',
  path: '/dashboard/add',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardAdminRoute = AuthDashboardAdminRouteImport.update({
  id: '/dashboard_/admin',
  path: '/dashboard/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCachePurgeRoute = ApiCachePurgeRouteImport.update({
  id: '/api/cache/purge',
  path: '/api/cache/purge',
  getParentRoute: () => rootRouteImport,
} as any)
const BabyPublicIdIndexRoute = BabyPublicIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BabyPublicIdRouteRoute,
} as any)
const BabyPublicIdPhotoRoute = BabyPublicIdPhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => BabyPublicIdRouteRoute,
} as any)
const BabyPublicIdPostRoute = BabyPublicIdPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => BabyPublicIdRouteRoute,
} as any)
const BabyPublicIdSettingsRoute = BabyPublicIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BabyPublicIdRouteRoute,
} as any)
const BabyPublicIdShareRoute = BabyPublicIdShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => BabyPublicIdRouteRoute,
} as any)
const BabyManifest_idRoute = BabyManifest_idRouteImport.update({
  id: '/baby/manifest/$_id',
  path: '/baby/manifest/$_id',
  getParentRoute: () => rootRouteImport,
} as any)
const OgBabyPublicIdRoute = OgBabyPublicIdRouteImport.update({
  id: '/baby/$publicId',
  path: '/baby/$publicId',
  getParentRoute: () => OgRoute,
} as any)
const BabyPublicIdUpdatesUpdateIdPhotoRoute =
  BabyPublicIdUpdatesUpdateIdPhotoRouteImport.update({
    id: '/updates/$updateId/photo',
    path: '/updates/$updateId/photo',
    getParentRoute: () => BabyPublicIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/og': typeof OgRouteWithChildren
  '/preview': typeof PreviewRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/baby/$publicId': typeof BabyPublicIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard/add': typeof AuthDashboardAddRoute
  '/dashboard/admin': typeof AuthDashboardAdminRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/purge': typeof ApiCachePurgeRoute
  '/baby/$publicId/photo': typeof BabyPublicIdPhotoRoute
  '/baby/$publicId/post': typeof BabyPublicIdPostRoute
  '/baby/$publicId/settings': typeof BabyPublicIdSettingsRoute
  '/baby/$publicId/share': typeof BabyPublicIdShareRoute
  '/baby/manifest/$_id': typeof BabyManifest_idRoute
  '/og/baby/$publicId': typeof OgBabyPublicIdRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/baby/$publicId/': typeof BabyPublicIdIndexRoute
  '/baby/$publicId/updates/$updateId/photo': typeof BabyPublicIdUpdatesUpdateIdPhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og': typeof OgRouteWithChildren
  '/preview': typeof PreviewRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard/add': typeof AuthDashboardAddRoute
  '/dashboard/admin': typeof AuthDashboardAdminRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/purge': typeof ApiCachePurgeRoute
  '/baby/$publicId/photo': typeof BabyPublicIdPhotoRoute
  '/baby/$publicId/post': typeof BabyPublicIdPostRoute
  '/baby/$publicId/settings': typeof BabyPublicIdSettingsRoute
  '/baby/$publicId/share': typeof BabyPublicIdShareRoute
  '/baby/manifest/$_id': typeof BabyManifest_idRoute
  '/og/baby/$publicId': typeof OgBabyPublicIdRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/baby/$publicId': typeof BabyPublicIdIndexRoute
  '/baby/$publicId/updates/$updateId/photo': typeof BabyPublicIdUpdatesUpdateIdPhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/og': typeof OgRouteWithChildren
  '/preview': typeof PreviewRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/baby/$publicId': typeof BabyPublicIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_auth/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/_auth/dashboard_/add': typeof AuthDashboardAddRoute
  '/_auth/dashboard_/admin': typeof AuthDashboardAdminRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/purge': typeof ApiCachePurgeRoute
  '/baby/$publicId/photo': typeof BabyPublicIdPhotoRoute
  '/baby/$publicId/post': typeof BabyPublicIdPostRoute
  '/baby/$publicId/settings': typeof BabyPublicIdSettingsRoute
  '/baby/$publicId/share': typeof BabyPublicIdShareRoute
  '/baby/manifest/$_id': typeof BabyManifest_idRoute
  '/og/baby/$publicId': typeof OgBabyPublicIdRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/baby/$publicId/': typeof BabyPublicIdIndexRoute
  '/baby/$publicId/updates/$updateId/photo': typeof BabyPublicIdUpdatesUpdateIdPhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/og'
    | '/preview'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/dashboard'
    | '/baby/$publicId'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/dashboard/add'
    | '/dashboard/admin'
    | '/api/auth/$'
    | '/api/cache/purge'
    | '/baby/$publicId/photo'
    | '/baby/$publicId/post'
    | '/baby/$publicId/settings'
    | '/baby/$publicId/share'
    | '/baby/manifest/$_id'
    | '/og/baby/$publicId'
    | '/dashboard/'
    | '/baby/$publicId/'
    | '/baby/$publicId/updates/$updateId/photo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/og'
    | '/preview'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/settings'
    | '/dashboard/add'
    | '/dashboard/admin'
    | '/api/auth/$'
    | '/api/cache/purge'
    | '/baby/$publicId/photo'
    | '/baby/$publicId/post'
    | '/baby/$publicId/settings'
    | '/baby/$publicId/share'
    | '/baby/manifest/$_id'
    | '/og/baby/$publicId'
    | '/dashboard'
    | '/baby/$publicId'
    | '/baby/$publicId/updates/$updateId/photo'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/og'
    | '/preview'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_auth/dashboard'
    | '/baby/$publicId'
    | '/auth/login'
    | '/auth/signup'
    | '/_auth/dashboard/settings'
    | '/_auth/dashboard_/add'
    | '/_auth/dashboard_/admin'
    | '/api/auth/$'
    | '/api/cache/purge'
    | '/baby/$publicId/photo'
    | '/baby/$publicId/post'
    | '/baby/$publicId/settings'
    | '/baby/$publicId/share'
    | '/baby/manifest/$_id'
    | '/og/baby/$publicId'
    | '/_auth/dashboard/'
    | '/baby/$publicId/'
    | '/baby/$publicId/updates/$updateId/photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OgRoute: typeof OgRouteWithChildren
  PreviewRoute: typeof PreviewRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BabyPublicIdRouteRoute: typeof BabyPublicIdRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCachePurgeRoute: typeof ApiCachePurgeRoute
  BabyManifest_idRoute: typeof BabyManifest_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baby/$publicId': {
      id: '/baby/$publicId'
      path: '/baby/$publicId'
      fullPath: '/baby/$publicId'
      preLoaderRoute: typeof BabyPublicIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard/settings': {
      id: '/_auth/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthDashboardSettingsRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/dashboard_/add': {
      id: '/_auth/dashboard_/add'
      path: '/dashboard/add'
      fullPath: '/dashboard/add'
      preLoaderRoute: typeof AuthDashboardAddRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard_/admin': {
      id: '/_auth/dashboard_/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthDashboardAdminRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cache/purge': {
      id: '/api/cache/purge'
      path: '/api/cache/purge'
      fullPath: '/api/cache/purge'
      preLoaderRoute: typeof ApiCachePurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baby/$publicId/': {
      id: '/baby/$publicId/'
      path: '/'
      fullPath: '/baby/$publicId/'
      preLoaderRoute: typeof BabyPublicIdIndexRouteImport
      parentRoute: typeof BabyPublicIdRouteRoute
    }
    '/baby/$publicId/photo': {
      id: '/baby/$publicId/photo'
      path: '/photo'
      fullPath: '/baby/$publicId/photo'
      preLoaderRoute: typeof BabyPublicIdPhotoRouteImport
      parentRoute: typeof BabyPublicIdRouteRoute
    }
    '/baby/$publicId/post': {
      id: '/baby/$publicId/post'
      path: '/post'
      fullPath: '/baby/$publicId/post'
      preLoaderRoute: typeof BabyPublicIdPostRouteImport
      parentRoute: typeof BabyPublicIdRouteRoute
    }
    '/baby/$publicId/settings': {
      id: '/baby/$publicId/settings'
      path: '/settings'
      fullPath: '/baby/$publicId/settings'
      preLoaderRoute: typeof BabyPublicIdSettingsRouteImport
      parentRoute: typeof BabyPublicIdRouteRoute
    }
    '/baby/$publicId/share': {
      id: '/baby/$publicId/share'
      path: '/share'
      fullPath: '/baby/$publicId/share'
      preLoaderRoute: typeof BabyPublicIdShareRouteImport
      parentRoute: typeof BabyPublicIdRouteRoute
    }
    '/baby/manifest/$_id': {
      id: '/baby/manifest/$_id'
      path: '/baby/manifest/$_id'
      fullPath: '/baby/manifest/$_id'
      preLoaderRoute: typeof BabyManifest_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/baby/$publicId': {
      id: '/og/baby/$publicId'
      path: '/baby/$publicId'
      fullPath: '/og/baby/$publicId'
      preLoaderRoute: typeof OgBabyPublicIdRouteImport
      parentRoute: typeof OgRoute
    }
    '/baby/$publicId/updates/$updateId/photo': {
      id: '/baby/$publicId/updates/$updateId/photo'
      path: '/updates/$updateId/photo'
      fullPath: '/baby/$publicId/updates/$updateId/photo'
      preLoaderRoute: typeof BabyPublicIdUpdatesUpdateIdPhotoRouteImport
      parentRoute: typeof BabyPublicIdRouteRoute
    }
  }
}

interface AuthDashboardRouteRouteChildren {
  AuthDashboardSettingsRoute: typeof AuthDashboardSettingsRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
}

const AuthDashboardRouteRouteChildren: AuthDashboardRouteRouteChildren = {
  AuthDashboardSettingsRoute: AuthDashboardSettingsRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
}

const AuthDashboardRouteRouteWithChildren =
  AuthDashboardRouteRoute._addFileChildren(AuthDashboardRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthDashboardRouteRoute: typeof AuthDashboardRouteRouteWithChildren
  AuthDashboardAddRoute: typeof AuthDashboardAddRoute
  AuthDashboardAdminRoute: typeof AuthDashboardAdminRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRouteRoute: AuthDashboardRouteRouteWithChildren,
  AuthDashboardAddRoute: AuthDashboardAddRoute,
  AuthDashboardAdminRoute: AuthDashboardAdminRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OgRouteChildren {
  OgBabyPublicIdRoute: typeof OgBabyPublicIdRoute
}

const OgRouteChildren: OgRouteChildren = {
  OgBabyPublicIdRoute: OgBabyPublicIdRoute,
}

const OgRouteWithChildren = OgRoute._addFileChildren(OgRouteChildren)

interface BabyPublicIdRouteRouteChildren {
  BabyPublicIdPhotoRoute: typeof BabyPublicIdPhotoRoute
  BabyPublicIdPostRoute: typeof BabyPublicIdPostRoute
  BabyPublicIdSettingsRoute: typeof BabyPublicIdSettingsRoute
  BabyPublicIdShareRoute: typeof BabyPublicIdShareRoute
  BabyPublicIdIndexRoute: typeof BabyPublicIdIndexRoute
  BabyPublicIdUpdatesUpdateIdPhotoRoute: typeof BabyPublicIdUpdatesUpdateIdPhotoRoute
}

const BabyPublicIdRouteRouteChildren: BabyPublicIdRouteRouteChildren = {
  BabyPublicIdPhotoRoute: BabyPublicIdPhotoRoute,
  BabyPublicIdPostRoute: BabyPublicIdPostRoute,
  BabyPublicIdSettingsRoute: BabyPublicIdSettingsRoute,
  BabyPublicIdShareRoute: BabyPublicIdShareRoute,
  BabyPublicIdIndexRoute: BabyPublicIdIndexRoute,
  BabyPublicIdUpdatesUpdateIdPhotoRoute: BabyPublicIdUpdatesUpdateIdPhotoRoute,
}

const BabyPublicIdRouteRouteWithChildren =
  BabyPublicIdRouteRoute._addFileChildren(BabyPublicIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OgRoute: OgRouteWithChildren,
  PreviewRoute: PreviewRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BabyPublicIdRouteRoute: BabyPublicIdRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCachePurgeRoute: ApiCachePurgeRoute,
  BabyManifest_idRoute: BabyManifest_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
